sim_config:
  sim_time: 25.0 # seconds
  max_speed: 1.0 # m/s
  waypoints:
    - [0.0, 0.0, 1.0]
    - [5.0, 5.0, 1.0]
    - [0.0, 0.0, 1.0]
  path_facing: true
controller:
  solver_definition_path: 'solver_definition_mpc_position.yaml'
  ocp_json_file_path: 'acados_position_mpc/mpc_generated_code/acados_ocp.json'
  mpc:
    dt: 0.2 # Delta time between control steps in seconds
    Q: [2.5, 2.5, 5.0, 0.1, 0.1, 15.0, 0.1, 0.1, 0.1] # Weight for internal states: [x, y, z, roll, pitch, yaw, vx, vy, vz]
    Qe: [10.0, 10.0, 30.0, 0.1, 0.1, 15.0, 0.1, 0.1, 0.1] # Weight for end states: [x, y, z, roll, pitch, yaw, vx, vy, vz]
    R: [0.8, 1.0, 1.0, 0.1] # Weight for control inputs: [thrust, wx, wy, wz]
    lbu: [0.01, -2.0, -2.0, -0.5] # Lower bounds for control inputs: [thrust, wx, wy, wz]
    ubu: [40.0, 2.0, 2.0, 0.5] # Upper bounds for control inputs: [thrust, wx, wy, wz]
    lbx: [-0.5, -0.5, -0.5] # Lower bounds for states: [vx, vy, vz]
    ubx: [0.5, 0.5, 0.5] # Upper bounds for states: [vx, vy, vz]
    lsbx: [-2.0, -2.0, -2.0] # Lower soft bounds for states: [vx, vy, vz]
    usbx: [2.0, 2.0, 2.0] # Upper soft bounds for states: [vx, vy, vz]
    Zl: [100.0, 100.0, 100.0] # Diagonal Hessian weights for lower slack variables (dimension = nsbx)
    Zu: [100.0, 100.0, 100.0] # Diagonal Hessian weights for upper slack variables (dimension = nsbx)
    zl: [10.0, 10.0, 10.0] # Linear weights for lower slack variables (dimension = nsbx)
    zu: [10.0, 10.0, 10.0] # Linear weights for upper slack variables (dimension = nsbx)
    Zl_e: [100.0, 100.0, 100.0] # Diagonal Hessian weights for lower slack variables at terminal shooting node (N) (dimension = nsbx_e)
    Zu_e: [100.0, 100.0, 100.0] # Diagonal Hessian weights for upper slack variables at terminal shooting node (N) (dimension = nsbx_e)
    zl_e: [10.0, 10.0, 10.0] # Linear weights for lower slack variables at terminal shooting node (N) (dimension = nsbx_e)
    zu_e: [10.0, 10.0, 10.0] # Linear weights for upper slack variables at terminal shooting node (N) (dimension = nsbx_e)
    p: [1.0, 1.0, 0.0, 0.0, 0.0] # Online parameter: [mass, ref_orientation (qw, qx, qy, qz)]