sim_config:
  sim_time: 40.0 # seconds
  max_speed: 1.0 # m/s
  waypoints:
    - [0.0, 0.0, 10.0]
    - [0.0, 0.0, 20.0]
    - [0.0, 0.0, 30.0]
    # - [0.0, 0.0, 100.0]
    # - [0.0, 0.0, 100.0]
    # - [0.0, 0.0, 100.0]
    # - [0.0, 0.0, 200.0]
    # - [0.0, 0.0, 200.0]
    # - [0.0, 0.0, 200.0]
    # - [0.0, 0.0, 200.0]
    # - [0.0, 0.0, 200.0]
    # - [0.0, 0.0, 200.0]
    # - [0.0, 0.0, 300.0]
    # - [0.0, 0.0, 300.0]
    # - [0.0, 0.0, 300.0]
    # - [0.0, 0.0, 300.0]
    # - [0.0, 0.0, 300.0]
    # - [0.0, 0.0, 300.0]
  path_facing: true
controller:
  solver_definition_path: 'solver_definition_mpc_position.yaml'
  ocp_json_file_path: 'acados_position_mpc/mpc_generated_code/acados_ocp.json'
  mpc:
    parameters:
      mass: [1.0] # Mass of the MAV (kg)
    cost:
      # Weight for internal states: [x, y, z, roll, pitch, yaw, vx, vy, vz]
      Q: [2.5, 2.5, 5.0, 0.1, 0.1, 10.0, 0.1, 0.1, 0.1]
      # Weight for end states: [x, y, z, roll, pitch, yaw, vx, vy, vz]
      Qe: [10.0, 10.0, 20.0, 0.1, 0.1, 20.0, 0.1, 0.1, 0.1]
      # Weight for control inputs: [thrust, wx, wy, wz]
      R: [0.5, 1.0, 1.0, 0.5]
    constraints:
      # Lower bounds for control inputs: [thrust, wx, wy, wz]
      lbu: [0.01, -3.0, -3.0, -2.0]
      # Upper bounds for control inputs: [thrust, wx, wy, wz]
      ubu: [35.0, 3.0, 3.0, 2.0]
      # Lower bounds for states: [x, y, z, qw, qx, qy, qz, vx, vy, vz]
      lbx: [-0.5, -0.5, -0.5]
      # Upper bounds for states: [x, y, z, qw, qx, qy, qz, vx, vy, vz]
      ubx: [0.5, 0.5, 0.5]
      # Diagonal Hessian weights for lower slack variables
      Zl: [100.0, 100.0, 100.0]
      # Diagonal Hessian weights for upper slack variables
      Zu: [100.0, 100.0, 100.0]
      # Linear weights for lower slack variables
      zl: [1.0, 1.0, 1.0]
      # Linear weights for upper slack variables
      zu: [1.0, 1.0, 1.0]
