#!/usr/bin/env python3

# Copyright 2025 Universidad Politécnica de Madrid
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
#    * Neither the name of the Universidad Politécnica de Madrid nor the names of its
#      contributors may be used to endorse or promote products derived from
#      this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
"""Casadi MAV Model datatype Actuation."""

__authors__ = 'Rafael Pérez Seguí'
__copyright__ = 'Copyright (c) 2025 Universidad Politécnica de Madrid'
__license__ = 'BSD-3-Clause'

# THIS CODE HAS BEEN AUTOMATICALLY GENERATED USING templ_model_definition.py.j2

from typing import ClassVar, List, Union

from mpc_position.utils.datatypes_utils import VectorBase
import casadi as ca
import numpy as np


class _ActuationDef:
    """Actuation definition for MAV."""

    _names: ClassVar[List[str]] = [
        'thrust',
        'angular_velocity'
    ]
    _names_sx: ClassVar[List[str]] = [
        'sx_thrust',
        'sx_angular_velocity'
    ]
    _sizes: ClassVar[List[int]] = [
        1,
        3
    ]

    thrust: Union[ca.SX, ca.DM]
    angular_velocity: Union[ca.SX, ca.DM]


class CaActuation(_ActuationDef, VectorBase):
    """
    CasADi SX Actuation for the UAV.

    :param thrust: Total thrust generated by the motors (N)
    :type thrust: ca.SX
    :param angular_velocity: Angular velocity in body frame [wx, wy, wz] (rad/s)
    :type angular_velocity: ca.SX
    """

    _type = 'ca.SX'


class Actuation(_ActuationDef, VectorBase):
    """Actuation for the UAV Model."""

    _type = 'np.array'

    def __init__(
            self,
            thrust: np.array = np.array(0.0),
            angular_velocity: np.array = np.array([0.0, 0.0, 0.0])):
        """
        Actuation for the UAV Model.

        :param thrust: Total thrust generated by the motors (N)
        :type thrust: np.array
        :param angular_velocity: Angular velocity in body frame [wx, wy, wz] (rad/s)
        :type angular_velocity: np.array
        """
        super().__init__()
        self.thrust = thrust
        self.angular_velocity = angular_velocity


if __name__ == '__main__':
    # Test the Actuation class
    actuation = Actuation()
    print('CasADi SX:', actuation._names)
    print('CasADi SX Sizes:', actuation._sizes)
    print('Vector:', actuation.vector)
    print('thrust:', actuation.thrust)
    print('angular_velocity:', actuation.angular_velocity)
    print(actuation)
