
# If c_generated_code folder does not exist, create it using python3 mpc/mpc_controller.py
if(NOT EXISTS "${PROJECT_SOURCE_DIR}/mpc_generated_code")
  # export PYTHONPATH=$PYTHONPATH:${ACADOS_DIR}/interfaces/acados_template/
  set(ENV{PYTHONPATH} "$ENV{PYTHONPATH}:${ACADOS_DIR}/interfaces/acados_template/")
  # export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"${ACADOS_DIR}/lib"
  set(ENV{LD_LIBRARY_PATH} "$ENV{LD_LIBRARY_PATH}:${ACADOS_DIR}/lib")


  execute_process(COMMAND python3 mpc/mpc_controller.py
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}"
    RESULT_VARIABLE result)
  if(result)
    message(FATAL_ERROR "Failed to generate c code")
  endif()
endif()

set(ACADOS_C_GENERATED_CODE "${PROJECT_SOURCE_DIR}/mpc_generated_code")
set(ACADOS_C_GENERATED_CODE_LIB
  "${PROJECT_SOURCE_DIR}/mpc_generated_code/mpc_generated_code/libacados_ocp_solver_mpc.so"
  "${PROJECT_SOURCE_DIR}/mpc_generated_code/mpc_generated_code/libacados_sim_solver_mpc.so"
)


# Include c code generated by acados
include_directories(
	${ACADOS_C_GENERATED_CODE}
)
