// Copyright 2025 Universidad Politécnica de Madrid
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//    * Redistributions of source code must retain the above copyright
//      notice, this list of conditions and the following disclaimer.
//
//    * Redistributions in binary form must reproduce the above copyright
//      notice, this list of conditions and the following disclaimer in the
//      documentation and/or other materials provided with the distribution.
//
//    * Neither the name of the Universidad Politécnica de Madrid nor the names
//      of its contributors may be used to endorse or promote products derived
//      from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.

// This file was generated by mpc_acados_core.generate. Do not edit manually.

#ifndef MPC_ACADOS_POSITION_ACADOS_SIM_SOLVER_HPP_
#define MPC_ACADOS_POSITION_ACADOS_SIM_SOLVER_HPP_

#include <acados_c/external_function_interface.h>
#include <acados_c/ocp_nlp_interface.h>
#include <mpc_generated_code/acados_sim_solver_mpc.h>
#include <mpc_generated_code/acados_solver_mpc.h>
#include <mpc_generated_code/mpc_model/mpc_model.h>

#include <array>
#include <iostream>
#include <stdexcept>

#include "mpc_acados_position/acados_mpc.hpp"

namespace acados_mpc {

/**
 * @brief MPCSimSolver
 *
 * Wrapper around the acados generated sim solver used as a ground-truth
 * integrator for examples and tests.
 */
class MPCSimSolver {
public:
  MPCSimSolver();
  ~MPCSimSolver();

  /**
   * @brief Advance the integrator one step using the state and actuation of
   * ``data``. Writes the resulting state back to ``data``.
   */
  int solve(MPCData* data);

private:
  void initializeSolver();

  inline void validateStatus(const int status) {
    if (status) {
      std::cerr << "acados_create() returned status " << status << std::endl;
    }
  }

private:
  mpc_sim_solver_capsule* capsule_ = nullptr;
  sim_in* sim_in_ = nullptr;
  sim_out* sim_out_ = nullptr;

  int status_ = 0;
};

}  // namespace acados_mpc

#endif  // MPC_ACADOS_POSITION_ACADOS_SIM_SOLVER_HPP_

